title: Homebrew Formulae
description: Homebrew's package index

remote_theme: Homebrew/brew-sh

exclude:
  - bin
  - script
  - Rakefile
  - Gemfile*
  - vendor

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: https://brew.sh/assets/img/homebrew-256x256.png

logo: https://brew.sh/assets/img/homebrew-256x256.png

twitter:
  username: MacHomebrew

facebook:
  publisher: https://www.facebook.com/machomebrew/
