trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    HOMEBREW_REPOSITORY="$HOME/Homebrew"
    export PATH="$HOMEBREW_REPOSITORY/bin:$PATH"
    rm -rf $HOMEBREW_REPOSITORY
    git clone --depth=1 https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
    HOMEBREW_CORE_TAP_DIR="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core"
    mkdir -p "$HOMEBREW_CORE_TAP_DIR"
    rm -rf "$HOMEBREW_CORE_TAP_DIR"
    git clone --depth=1 https://github.com/Homebrew/homebrew-core "$HOMEBREW_CORE_TAP_DIR"
    export HOMEBREW_NO_ANALYTICS=1
    # trigger vendored ruby installation
    brew help
  displayName: 'Install Homebrew'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.3'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    HOMEBREW_REPOSITORY="$HOME/Homebrew"
    export PATH="$HOMEBREW_REPOSITORY/bin:$PATH"
    bundle exec rake
  displayName: 'bundle exec rake test'
