name: CI
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: true
          test-bot: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899 # v1.173.0
        with:
          bundler-cache: true

      - name: Generate formulae, casks and API samples
        run: /usr/bin/rake formulae casks api_samples
        env:
          HOMEBREW_DEVELOPER: 1

      - name: Generate analytics
        if: github.event.pull_request.head.repo.fork == false && (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]')
        run: |
          brew tap Homebrew/formula-analytics
          brew formula-analytics --install --json --days-ago=2
        env:
          HOMEBREW_INFLUXDB_TOKEN: ${{ secrets.HOMEBREW_INFLUXDB_READ_TOKEN }}

      - name: Build site
        run: bundle exec jekyll build

      - name: Validate build
        run: ./script/validate-build.rb
